services:
  - type: web
    name: receipt-ai-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11.0
