[global]
# Development mode - set to false for production
developmentMode = false

# Data directory for caching
dataDir = "~/.streamlit"

[logger]
# Logging level for production
level = "info"

[client]
# Disable usage stats collection for privacy
gatherUsageStats = false

# Show error details in production
showErrorDetails = true

# Toolbar mode for cloud deployment
toolbarMode = "minimal"

[server]
# Server settings optimized for Streamlit Cloud
port = 8501
enableCORS = true
enableXsrfProtection = true

# File upload settings
maxUploadSize = 200
maxMessageSize = 200

# Memory and performance settings
runOnSave = false
allowRunOnSave = false

# Enable WebSocket compression for better performance
enableWebsocketCompression = true

# Headless mode for cloud deployment
headless = true

# Base URL path (useful if deployed behind a proxy)
baseUrlPath = ""

# Disable static file serving to avoid warnings
enableStaticServing = false

[browser]
# Disable automatic browser opening in cloud environment
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# Custom theme for professional appearance
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Magic commands and performance settings
magicEnabled = true
installTracer = false
fixMatplotlib = true

# Faster reruns
fastReruns = true

# Enforce serializable session state
enforceSerializableSessionState = false

[mapbox]
# Disable mapbox token requirement
token = ""

[deprecation]
# Handle deprecation warnings
showPyplotGlobalUse = false
showfileUploaderEncoding = false
